### ISSUE TITLE
build: yarn install triggers yarn run build

### ISSUE THREAD

**Issue by s-pace** [francoischalifour/autocomplete.js#70]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**

When trying ton install this project thanks to `yarn install`, it seems that `yarn buid`. I do not expect such behaviour. 

![image](https://user-images.githubusercontent.com/32097720/90732145-f468c700-e2ca-11ea-9b56-f0ac4aa59ef6.png)

**What is the expected behavior?**
`yarn install` is not building this project

## Environment:

I am using node version 12.14.1 and yarn version 1.22.4

**Comment by francoischalifour** [comment]
The build after installing is triggered by the npm [`prepare` script](https://github.com/francoischalifour/autocomplete.js/blob/6bd21fc67451058f32460b1afaf65ae3a73ce71c/package.json#L8).

This is intended in this monorepo because Yarn needs to link the packages by building their ESM versions to be aware of their existence.
